# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: templateable 0.1.5 ruby lib

Gem::Specification.new do |s|
  s.name = "templateable"
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Mark Serrano"]
  s.date = "2015-12-01"
  s.description = "This gem enables adding fields to models via object fields"
  s.email = "mark@publicstuff.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/generators/templateable/install/install_generator.rb",
    "lib/generators/templateable/install/templates/create_object_field_associations.rb",
    "lib/generators/templateable/install/templates/create_object_field_instances.rb",
    "lib/generators/templateable/install/templates/create_object_field_options.rb",
    "lib/generators/templateable/install/templates/create_object_fields.rb",
    "lib/templateable.rb",
    "lib/templateable/object_fieldable.rb",
    "lib/templateable/templateable.rb",
    "lib/templateable/templateable_controller.rb",
    "templateable.gemspec",
    "test/helper.rb",
    "test/test_templateable.rb"
  ]
  s.homepage = "http://github.com/publicstuff/templateable"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.3"
  s.summary = "Allows templating by adding object fields"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 4.0.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, "~> 6.3")
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 4.0.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, "~> 6.3")
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 4.0.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, "~> 6.3")
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

